spring:
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
  cloud:
    gcp:
      project-id: skyscanner-287223
  main:
    web-application-type: none

bigquery:
  table-id: quotes
  dataset-id: skyscanner

pubsub:
  topic: projects/skyscanner-287223/topics/job-completion
  message: complete

delay: 1300
days: 120

cities:
  from: Helsinki, Tallinn, Stockholm, Oslo, Copenhagen, Riga, Minsk, Kaliningrad, Warsaw, Prague, Berlin, Hamburg, Hanover, Bremen, Leipzig, Dresden, Dortmund, Munich, Vienna, Budapest, Zagreb, Split, Belgrade, Sofia, Varna, Istanbul, Budva, San Marino, Rome, Milano, Naples, Florence, Palermo, Catania, Genoa, Zurich, Geneva, Nice, Marseille, Lyon, Paris, Toulouse, Barcelona, Zaragoza, Madrid, Valencia, Malaga, Seville, Bilbao, Lisbon, Porto, London, Manchester, Liverpool, Reykjavik
  to: Los Angeles, Saint Petersburg